<?php
return [
    //投屏语言包
    "万佳安·值得看大数据"    => "WorthCloud·Echodata",
    "万佳安·值得看智慧门店"    => "Passenger-flow Statistics",
    "简播·值得看大数据"   => "Jianbo·Echodata",
    "简播·值得看智慧门店"    => "Passenger-flow Statistics",

    "值得看·回响大数据" =>	"WorthCloud·Echodata",
    "智慧门店客流统计"  =>	"Passenger-flow Statistics",
    "访客统计"          =>	"Statistics on Visit Guest",
    "人"               =>	"in total",
    "人数"             =>    "",
    "当日进店人数"    =>	"Passenger-flow Today",
    "总到访"   =>	"Total Visits",
    //次	无需翻译
    "次"         => "",
    "年龄分布"  =>	"Age Distribution",
    "性别分布"  =>	"Gender Distribution",
    "新老客户比例"    =>	"Customer Analysis",
    "实时客流监控"    =>	"Real-Time Data of Passenger-flow",
    "星期一"   =>	"Monday",
    "星期二"   =>	"Tuesday",
    "星期三"   =>	"Wednesday",
    "星期四"   =>	"Thursday",
    "星期五"   =>	"Friday",
    "星期六"   =>	"Saturday",
    "星期天"   =>	"Sunday",
    "访客"     =>	"Vistor",
    "员工"     =>	"Staff",
    "会员"     =>	"VIP",
    "岁"       =>	"",
    "60岁以上"     =>	"60+",
    "访问人次"  =>	"Visits",
    "性别"     =>    "Gender",
    "新客户"   =>	"The News",
    "老客户"   =>	"The Regulars",
    "女士"     =>	"Female",
    "男士"     =>	"Male",
    'BI商业智能系统' => 'WorthCloud·Echodata_',

    //api新添加的
    '其它'    => 'other',
    '愤怒'    => 'anger',
    '厌恶'    => 'disgust',
    '恐惧'    => 'fear',
    '高兴'    => 'happiness',
    '平静'    => 'Calm',
    '伤心'    => 'Grieved',
    '惊讶'    => 'surprise',
    '抬头'    => 'pitch_angle',
    '摇头'    => 'yaw_angle',
    '亚洲人'   => 'asian',
    '白人'    => 'white',
    '黑人'    => 'black',
    ];
?>